-- ═══════════════════════════════════════════════════════════════════════
-- VIGIA 360 · Plan Anual de Trabajo (PAT) — Migración Supabase
-- Ejecutar en: Supabase → SQL Editor
-- ═══════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS pat_actividades (
  id                  SERIAL PRIMARY KEY,
  empresa_nombre      TEXT NOT NULL,
  empresa_nit         TEXT,
  año                 SMALLINT NOT NULL DEFAULT 2022,
  responsable_sgsst   TEXT,
  representante_legal TEXT,
  ciclo_phva          TEXT NOT NULL CHECK(ciclo_phva IN ('PLANEAR','HACER','VERIFICAR','ACTUAR')),
  objetivo            TEXT,
  meta                TEXT,
  actividad           TEXT NOT NULL,
  responsable         TEXT,
  meses_programados   TEXT[] DEFAULT '{}',
  meses_ejecutados    TEXT[] DEFAULT '{}',
  r_fisicos           BOOLEAN DEFAULT false,
  r_economicos        BOOLEAN DEFAULT false,
  r_humanos           BOOLEAN DEFAULT false,
  indicador           TEXT,
  formula             TEXT,
  entregable          TEXT,
  observaciones       TEXT,
  activo              BOOLEAN DEFAULT true,
  orden               SMALLINT DEFAULT 0,
  created_at          TIMESTAMPTZ DEFAULT NOW(),
  updated_at          TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE pat_actividades ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all pat" ON pat_actividades;
CREATE POLICY "Allow all pat" ON pat_actividades FOR ALL USING (true) WITH CHECK (true);

-- ── Datos iniciales: Fundación ProAves de Colombia 2022 ─────────────────

INSERT INTO pat_actividades
  (empresa_nombre,empresa_nit,año,responsable_sgsst,representante_legal,
   ciclo_phva,objetivo,meta,actividad,responsable,
   meses_programados,meses_ejecutados,r_fisicos,r_economicos,r_humanos,
   indicador,formula,entregable,orden)
VALUES

-- ── PLANEAR ──────────────────────────────────────────────────────────────
('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'PLANEAR',
 'Garantizar el compromiso para el mejoramiento continuo del desempeño en SST',
 'Divulgación de la política al 100% de los empleados y contratistas',
 'Actualizar la política de Seguridad y Salud en el Trabajo en compañía del COPASST. Publicar política de SST',
 'Gerencia, Responsable del SG-SST, COPASST',
 '{mar}','{}',false,false,true,
 '%Divulgación Política: #personas que conocen política / #Total empleados × 100',
 '(No. empleados que conocen la Política del SST / No. total de empleados) × 100',
 'Política firmada por gerencia. Registro de asistencia',1),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'PLANEAR',
 'Implementar y mantener el SG-SST para garantizar un ambiente de trabajo seguro y saludable',
 'Divulgación de los Objetivos del SG-SST al 100% de los empleados y contratistas',
 'Elaborar los Objetivos y metas de SST. Socializar los Objetivos del SG-SST',
 'Gerencia, Responsable del SG-SST, COPASST',
 '{mar}','{}',false,false,true,
 'Objetivos y metas de seguridad divulgados',
 '(No. empleados a los que se divulgó los objetivos SST / Promedio de empleados en el período) × 100',
 'Indicadores del SG-SST. Registro de asistencia',2),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'PLANEAR',
 'Garantizar el compromiso para el mejoramiento continuo del desempeño en SST',
 'Contar con responsable del SG-SST que cumpla los requisitos de la Resolución 0312 de 2019',
 'Asignar persona que diseñe el Sistema de Gestión de SST',
 'Gerencia',
 '{feb}','{feb}',true,true,true,
 'N/A','N/A',
 'SG_SST F001 Designación Responsable SST. Hoja de vida. Licencia SST. Curso 50 horas SG-SST',3),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'PLANEAR',
 'Implementar y mantener el SG-SST para garantizar un ambiente de trabajo seguro y saludable',
 'Cumplir con mínimo el 85% de los estándares mínimos según Resolución 0312 de 2019',
 'Implementar el SG-SST F005 Plan Anual de Trabajo del SG-SST',
 'COPASST, Responsable del SG-SST, Representante Legal, Comité de Convivencia Laboral',
 '{feb,mar,abr,may,jun,jul,ago,sep,oct,nov,dic}','{feb}',true,true,true,
 'Cumplimiento del Plan de Trabajo anual en SST',
 '(No. De actividades ejecutadas del Plan de Trabajo Anual / No. De actividades totales) × 100',
 'Sistema de Gestión en SST (Carpeta en Google Drive de la Fundación ProAves de Colombia)',4),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'PLANEAR',
 'Implementar y mantener el SG-SST para garantizar un ambiente de trabajo seguro y saludable',
 '100% de responsabilidades asignadas',
 'Definir los roles y responsabilidades en el SG-SST de todas las personas de la organización y socializarlas',
 'COPASST, Responsable del SG-SST, Representante Legal',
 '{abr}','{}',true,false,true,
 'Asignación de responsabilidades',
 '(N° total de cargos con delegación de responsabilidad en SGSST / Total de cargos de la empresa) × 100',
 'SG-SST F003 Asignación de Responsabilidades y Rendición de Cuentas. Registro de asistencia',5),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'PLANEAR',
 'Definir y asignar el talento humano y los recursos requeridos para la implementación del SG-SST',
 'Cumplir con el 90% del presupuesto asignado del SG-SST',
 'Elaborar el SG-SST F006 Presupuesto del SG-SST del año 2022',
 'Gerencia, Responsable del SG-SST, COPASST',
 '{mar}','{}',true,true,true,
 'N/A',
 '($ Total presupuesto ejecutado / $ total presupuestado) × 100',
 'SG-SST F006 Presupuesto del SG-SST del año 2022 firmado por Representante Legal y Responsable SG-SST',6),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'PLANEAR',
 'Garantizar el cumplimiento de los requisitos legales en materia de SST aplicables a la empresa',
 'Cumplir con el 100% de los requisitos legales en materia de Riesgos Laborales',
 'Definir la matriz legal que contemple las normas actualizadas del Sistema General de Riesgos Laborales',
 'Gerencia, Responsable del SG-SST',
 '{ene,feb,mar,abr,may,jun,jul,ago,sep,oct,nov,dic}','{}',true,true,true,
 'N/A',
 '(No. Requisitos legales que se cumple / No. Total de requisitos legales) × 100',
 'Matriz Legal de la Fundación ProAves',7),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'PLANEAR',
 'Garantizar el cumplimiento de los requisitos legales que en materia de SST apliquen a la empresa',
 'Aplicación del 100% de los aspectos de la línea basal según la Resolución 0312 de 2019',
 'Realizar la evaluación inicial del Sistema de Gestión de SST, identificando las prioridades',
 'Responsable del SG-SST',
 '{feb}','{feb}',false,false,true,
 'Evaluación inicial del SG-SST',
 '(No. De estándares mínimos que cumple / No. total de estándares que debe cumplir) × 100',
 'Autoevaluación 0312 de 2019',8),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'PLANEAR',
 'Garantizar el cumplimiento de los requisitos legales que en materia de SST apliquen a la empresa',
 '100% de los documentos asociados al SG-SST codificados',
 'Contar con un sistema de archivo y retención documental para los registros que soportan el SG-SST',
 'Responsable del SG-SST, COPASST',
 '{feb}','{feb}',true,false,true,
 'N/A',
 '(No. Documentos codificados asociados al SG-SST / No. Total de documentos del SG-SST) × 100',
 'SG-SST P004 Procedimiento de Control de la Documentación',9),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'PLANEAR',
 'Garantizar el cumplimiento de los requisitos legales que en materia de SST apliquen a la empresa',
 '100% de los empleados deben rendir cuentas sobre el desempeño del SG-SST',
 'Contar con un Procedimiento para la Rendición sobre el desempeño en el SG-SST',
 'Responsable del SG-SST, COPASST',
 '{feb}','{feb}',true,false,true,
 'N/A','N/A',
 'SG-SST P005 Procedimiento de Medición y seguimiento al desempeño',10),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'PLANEAR',
 'Garantizar el cumplimiento de los requisitos legales que en materia de SST apliquen a la empresa',
 '100% de los empleados deben conocer los mecanismos de comunicación y auto reporte en SG-SST',
 'Disponer de mecanismos eficaces para recibir y responder las comunicaciones internas y externas relativas al SST',
 'Responsable del SG-SST, COPASST',
 '{feb}','{feb}',true,false,true,
 'N/A','N/A',
 'SG-SST P002 Procedimiento de Comunicación Interna y Externa',11),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'PLANEAR',
 'Garantizar el cumplimiento de los requisitos legales que en materia de SST apliquen a la empresa',
 '80% de los proveedores en SST deben ser evaluados',
 'Diseñar el SG-SST P010 Procedimiento de Adquisiciones y Compras',
 'Responsable del SG-SST, COPASST',
 '{feb}','{feb}',true,false,true,
 'N/A','N/A',
 'SG-SST P010 Procedimiento de Adquisiciones y Compras',12),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'PLANEAR',
 'Establecer los objetivos y metas de los programas de prevención de riesgos y promoción de la salud',
 '90% de cumplimiento de los programas',
 'Definir programas de intervención de la accidentalidad según la identificación de peligros y riesgos',
 'Encargado del SG-SST',
 '{}','{}',false,false,false,
 'Cumplimiento de los planes de trabajo de los programas de gestión',
 'N/A','Programas de gestión de SST',13),

-- ── HACER ────────────────────────────────────────────────────────────────
('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'HACER',
 'Garantizar el cubrimiento de los trabajadores al Sistema General de Riesgos Laborales',
 '100% cobertura a la población trabajadora',
 'Realizar el pago a Salud, Pensiones y Riesgos Laborales',
 'Gerencia',
 '{ene,feb,mar,abr,may,jun,jul,ago,sep,oct,nov,dic}','{ene,feb,mar,abr}',false,true,true,
 'N/A',
 '(No. empleados afiliados al Sistema General de Riesgos Laborales / No. empleados de la empresa) × 100',
 'Planillas de Afiliación a la Seguridad Social',14),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'HACER',
 'Implementar y mantener el SG-SST para garantizar un ambiente de trabajo seguro y saludable',
 'Cumplir con el 100% de los requisitos de la Resolución 2013 de 1986 sobre COPASST',
 'Conformar el COPASST con vigencia 2022-2024',
 'COPASST, Responsable del SG-SST, Auxiliar administrativa',
 '{oct}','{}',false,false,false,
 'N/A','N/A',
 'SG-SST F004 Formato de designación del Vigía de SST',15),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'HACER',
 'Implementar y mantener el SG-SST para garantizar un ambiente de trabajo seguro y saludable',
 'Cumplir con el 100% de las reuniones programadas del COPASST',
 'Realizar reuniones mensuales del COPASST',
 'COPASST',
 '{ene,feb,mar,abr,may,jun,jul,ago,sep,oct,nov,dic}','{}',true,false,true,
 'Funcionamiento del COPASST',
 '(N° reuniones ejecutadas del COPASST / No. Reuniones programadas) × 100',
 'SG-SST F007 Acta de Reunión mensual',16),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'HACER',
 'Implementar y mantener el SG-SST para garantizar un ambiente de trabajo seguro y saludable',
 'Capacitar al COPASST',
 'Capacitar al COPASST según el Cronograma de Capacitaciones de la empresa',
 'COPASST',
 '{mar,abr}','{}',true,false,true,
 'Funcionamiento del COPASST',
 'N/A',
 'Certificado curso de las 50 horas del SG-SST',17),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'HACER',
 'Ejecutar un plan de capacitación y entrenamiento orientado a prevenir los peligros y riesgos',
 'Cumplir con el 80% del Programa de Capacitación',
 'Elaborar y ejecutar programa de capacitación en promoción y prevención, que incluya los peligros/riesgos prioritarios y las medidas de prevención y control',
 'Responsable del SG-SST y COPASST',
 '{feb,abr,may,jun,ago,sep,dic}','{}',true,true,true,
 'Cantidad de empleados capacitados en SST',
 '(N° empleados capacitados en SST / No. Total de empleados) × 100',
 'SG-SST F010 Cronograma de Capacitaciones en SST',18),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'HACER',
 'Implementar y mantener el SG-SST para garantizar un ambiente de trabajo seguro y saludable',
 'Cumplir con el 100% de los requisitos de la Resolución 0652 de 2012 y 1356 de 2012 sobre el CCL',
 'Conformar el Comité de Convivencia Laboral con vigencia 2022-2024',
 'Comité de Convivencia Laboral',
 '{oct}','{}',false,true,false,
 'N/A','N/A',
 'SG-SST F005 Formato de designación Vigía de Convivencia Laboral',19),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'HACER',
 'Implementar y mantener el SG-SST para garantizar un ambiente de trabajo seguro y saludable',
 'Cumplir con el 100% de las reuniones programadas del Comité de Convivencia Laboral',
 'Realizar reuniones trimestrales del Comité de Convivencia Laboral',
 'Comité de Convivencia Laboral',
 '{feb,may,ago,oct}','{}',true,false,true,
 'Funcionamiento del Vigía de Convivencia Laboral',
 '(N° reuniones ejecutadas del CCL / No. Reuniones programadas) × 100',
 'SG-SST F007 Acta de Reunión',20),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'HACER',
 'Garantizar el cumplimiento de los requisitos legales que en materia de SST apliquen a la empresa',
 '80% de los proveedores en SST deben ser evaluados',
 'Realizar Evaluación y Selección de Proveedores y Contratistas',
 'Responsable del SG-SST, COPASST',
 '{oct}','{}',true,false,true,
 'N/A',
 '(No. De proveedores en SST evaluados / No. Total de proveedores en SST) × 100',
 'SG-SST F024 Formato de selección, evaluación y reevaluación de proveedores',21),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'HACER',
 'Garantizar el cumplimiento de los requisitos legales que en materia de SST apliquen a la empresa',
 '100% de los impactos de cambios internos y externos del SG-SST deben ser evaluados',
 'Realizar evaluación de Impactos de Cambios Internos y Externos del SG-SST',
 'Responsable del SG-SST, COPASST',
 '{feb,mar,abr,may,jun,jul,ago,sep,oct,nov,dic}','{feb}',true,false,true,
 'N/A','N/A',
 'SG-SST P007 Procedimiento de Gestión del Cambio. SG-SST F018 Formato Gestión del Cambio',22),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'HACER',
 'Garantizar el cumplimiento de los requisitos legales que en materia de SST apliquen a la empresa',
 '100% de los empleados deben diligenciar la Encuesta del Perfil Sociodemográfico',
 'Diseñar y diligenciar la Encuesta del Perfil Sociodemográfico',
 'Responsable del SG-SST, COPASST',
 '{feb}','{feb}',true,false,true,
 'N/A','N/A',
 'SG-SST 003 Encuesta Sociodemográfica',23),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'HACER',
 'Evaluaciones médicas ocupacionales',
 '100% de los empleados con los exámenes Médicos Ocupacionales',
 'Todos los empleados de la empresa deben contar con los exámenes Médicos Ocupacionales',
 'COPASST, Representante Legal',
 '{feb}','{feb}',true,false,true,
 'N/A',
 '(No. Empleados que cuentan con el exámen ocupacional / No. Total de empleados) × 100',
 'Conceptos Médicos de los Exámenes Ocupacionales',24),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'HACER',
 'Garantizar el cumplimiento de los requisitos legales que en materia de SST apliquen a la empresa',
 'Cumplimiento del 100% de las restricciones o recomendaciones médicas laborales',
 'Solicitar a la IPS el soporte de la custodia de los exámenes médicos ocupacionales',
 'COPASST, Representante Legal',
 '{jun}','{}',true,false,true,
 'N/A','N/A',
 'Custodia de las historias clínicas',25),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'HACER',
 'Gestionar y controlar los peligros y riesgos',
 'Investigar el 100% de los eventos que se presenten',
 'Registrar, caracterizar y analizar la accidentalidad',
 'Encargado del SG-SST',
 '{mar,abr,may,jun,jul,ago,sep,oct,nov,dic}','{mar,abr,may,jun,jul,ago,sep,oct,nov,dic}',false,false,false,
 '%Investigación AT/IT: #eventos investigados / #total ocurridos',
 '(No. Accidentes e incidentes investigados / No. Total de accidentes e incidentes ocurridos) × 100',
 'Investigación de los Accidentes e incidentes laborales',26),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'HACER',
 'Gestionar y controlar los peligros y riesgos',
 'Caracterizar el 100% de las incapacidades por EL-ATEL',
 'Registrar, caracterizar y analizar el ausentismo',
 'Encargado del SG-SST',
 '{mar,abr,may,jun,jul,ago,sep,oct,nov,dic}','{mar,abr,may,jun,jul,ago,sep,oct,nov,dic}',false,false,false,
 'Ausentismo por causa médica',
 '(Número de días de ausencia por incapacidad / Número de días de trabajo programados en el mes) × 100',
 'Informe Mensual de Ausentismo',27),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'HACER',
 'Gestionar y controlar los peligros y riesgos',
 'Inducción al 100% de los empleados nuevos',
 'Dar inducción en seguridad y salud en el trabajo al personal nuevo y al personal que lo requiera',
 'Encargado del SG-SST',
 '{mar,abr,may,jun,jul,ago,sep,oct,nov,dic}','{}',false,false,false,
 'Cobertura Inducción',
 '(Número de personas que asisten a la inducción / Número de personas que ingresan en el período) × 100',
 'Listado de Asistencia Capacitación',28),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'HACER',
 'Gestionar y controlar los peligros y riesgos',
 'Cumplir con el 100% de las inspecciones programadas en el año',
 'Realizar inspección de seguridad',
 'COPASST, Encargado del SG-SST',
 '{abr,ago,nov}','{}',false,false,false,
 '%Inspecciones realizadas',
 '(Número de inspecciones realizadas / Número de inspecciones planeadas) × 100',
 'Informes de Inspección de Seguridad',29),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'HACER',
 'Establecer el Plan de emergencias',
 'Cumplir con el 100% de los requisitos en materia de Planes de Emergencia',
 'Realizar Análisis de vulnerabilidad y diseñar Plan de Emergencias',
 'COPASST, Encargado del SG-SST',
 '{jul}','{}',false,false,false,
 'Plan de emergencias',
 '(N° actividades ejecutadas del Plan de Emergencias / No. actividades planeadas) × 100',
 'Plan de Emergencias',30),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'HACER',
 'Establecer el Plan de emergencias',
 'Conformar equipos de apoyo para emergencias',
 'Conformar los equipos de apoyo (comité de emergencias, brigada, Coordinadores de Evacuación)',
 'COPASST, Encargado del SG-SST',
 '{jul}','{}',false,false,false,
 'Plan de emergencias',
 '(N° actividades ejecutadas del Plan de Emergencias / No. actividades planeadas) × 100',
 'Plan de Emergencias',31),

-- ── VERIFICAR ────────────────────────────────────────────────────────────
('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'VERIFICAR',
 'Verificar la pertinencia y eficacia del plan de emergencias',
 'Realizar por lo menos 1 vez al año simulacro',
 'Realizar simulacro de emergencias',
 'COPASST, Encargado del SG-SST',
 '{oct}','{}',false,false,false,
 'Simulacros',
 '(N° DE SIMULACROS REALIZADOS / NRO DE SIMULACROS PROGRAMADOS) × 100',
 'Informe de simulacro',32),

-- ── ACTUAR ───────────────────────────────────────────────────────────────
('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'ACTUAR',
 'Revisión por la gerencia',
 'Revisión anual de la alta dirección',
 'Revisión de la política anual',
 'Alta dirección y COPASST',
 '{oct}','{}',false,false,false,
 'Reunión realizada','N/A',
 'Acta de Revisión',33),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'ACTUAR',
 'Revisión por la gerencia',
 'Revisión anual de la alta dirección',
 'Evidenciar que se cumpla con la normatividad nacional vigente aplicable en materia de riesgos laborales',
 'Alta dirección y COPASST',
 '{oct}','{}',false,false,false,
 'N/A','N/A','Acta de Revisión',34),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'ACTUAR',
 'Revisión por la gerencia',
 'Revisión anual de la alta dirección',
 'Revisión de la identificación de peligros e identificación de riesgo y planes de acción',
 'Encargado del SG-SST',
 '{oct}','{}',false,false,false,
 'N/A','N/A','Informe',35),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'ACTUAR',
 'Revisión por la gerencia',
 'Revisión anual de la alta dirección',
 'Indicadores de estructura, impacto y resultados',
 'Encargado del SG-SST',
 '{oct}','{}',false,false,false,
 'N/A','N/A','Informe',36),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'ACTUAR',
 'Auditoría interna o externa',
 'Auditoría interna o externa cada año y seguimiento a las anteriores',
 'Auditoría: el cumplimiento de la política de seguridad y salud en el trabajo',
 'Auditor Externo o Interno',
 '{nov}','{}',false,false,false,
 'Auditoría Interna',
 '(No. Estándares mínimos del SG-SST que se cumplen / No. Estándares evaluados) × 100',
 'Informe de Auditoría Interna',37),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'ACTUAR',
 'Auditoría interna o externa',
 'Auditoría interna o externa cada año y seguimiento a las anteriores',
 'Auditoría: el resultado de los indicadores de estructura, proceso y resultado',
 'Auditor Externo o Interno',
 '{nov}','{}',false,false,false,
 'N/A','N/A','Informe de Auditoría Interna',38),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'ACTUAR',
 'Auditoría interna o externa',
 'Auditoría interna o externa cada año y seguimiento a las anteriores',
 'Auditoría: la participación de los trabajadores',
 'Auditor Externo o Interno',
 '{nov}','{}',false,false,false,
 'N/A','N/A','Informe de Auditoría Interna',39),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'ACTUAR',
 'Auditoría interna o externa',
 'Auditoría interna o externa cada año y seguimiento a las anteriores',
 'Auditoría: el desarrollo de la responsabilidad y la obligación de rendir cuentas',
 'Auditor Externo o Interno',
 '{nov}','{}',false,false,false,
 'N/A','N/A','Informe de Auditoría Interna',40),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'ACTUAR',
 'Auditoría interna o externa',
 'Auditoría interna o externa cada año y seguimiento a las anteriores',
 'Auditoría: el mecanismo de comunicación de los contenidos del SG-SST a los trabajadores',
 'Auditor Externo o Interno',
 '{nov}','{}',false,false,false,
 'N/A','N/A','Informe de Auditoría Interna',41),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'ACTUAR',
 'Auditoría interna o externa',
 'Auditoría interna o externa cada año y seguimiento a las anteriores',
 'Auditoría: la planificación, desarrollo y aplicación del SG-SST',
 'Auditor Externo o Interno',
 '{nov}','{}',false,false,false,
 'N/A','N/A','Informe de Auditoría Interna',42),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'ACTUAR',
 'Auditoría interna o externa',
 'Auditoría interna o externa cada año y seguimiento a las anteriores',
 'Auditoría: la gestión del cambio',
 'Auditor Externo o Interno',
 '{nov}','{}',false,false,false,
 'N/A','N/A','Informe de Auditoría Interna',43),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'ACTUAR',
 'Auditoría interna o externa',
 'Auditoría interna o externa cada año y seguimiento a las anteriores',
 'Auditoría: la consideración de la seguridad y salud en el trabajo en las nuevas adquisiciones',
 'Auditor Externo o Interno',
 '{nov}','{}',false,false,false,
 'N/A','N/A','Informe de Auditoría Interna',44),

('FUNDACIÓN PROAVES DE COLOMBIA','811.031.647-1',2022,
 'MARÍA SUSANA URIBE GALEANO','SARA INÉS LARA HERNÁNDEZ',
 'ACTUAR',
 'Auditoría interna o externa',
 'Auditoría interna o externa cada año y seguimiento a las anteriores',
 'Auditoría: el alcance y aplicación del SG-SST frente a los proveedores y contratistas',
 'Auditor Externo o Interno',
 '{nov}','{}',false,false,false,
 'N/A','N/A','Informe de Auditoría Interna',45);
